# Generated by Django 2.0.3 on 2018-05-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loty2', '0002_auto_20180510_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(max_length=10),
        ),
    ]
