# Generated by Django 2.0.3 on 2018-06-15 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loty2', '0006_captain_crewmember_flightcrew'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightcrew',
            old_name='member',
            new_name='members',
        ),
    ]
