# Generated by Django 2.0.3 on 2018-06-15 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loty2', '0007_auto_20180615_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_crew',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crew', to='loty2.FlightCrew'),
        ),
    ]
