# Generated by Django 2.0.3 on 2018-06-16 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loty2', '0008_flight_flight_crew'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightcrew',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flightcrew',
            name='captain',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loty2.Captain'),
        ),
        migrations.AlterField(
            model_name='flightcrew',
            name='members',
            field=models.ManyToManyField(default='', to='loty2.CrewMember'),
        ),
    ]
